name: prism
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.10.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # --- Core Engine ---
  dio: ^5.4.0
  json_path: ^0.7.2
  shared_preferences: ^2.2.2
  provider: ^6.1.1
  path_provider: ^2.1.2

  # --- UI ---
  cached_network_image: ^3.3.1
  flutter_staggered_grid_view: ^0.7.0
  permission_handler: ^10.2.0  # 申请权限
  gal: ^2.3.0  # 保存图片到相册
  share_plus: ^7.0.2           # 系统分享

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true